# Generated by Django 5.1.4 on 2025-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
