# Generated by Django 5.1.4 on 2025-02-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='User',
        ),
    ]
